name: libserialport
description: Serial Port for Dart (FFI bindings to libserialport, a minimal
  C-library created by the sigrok).
version: 0.2.0
homepage: https://github.com/jpnurmi/libserialport.dart
repository: https://github.com/jpnurmi/libserialport.dart
issue_tracker: https://github.com/jpnurmi/libserialport.dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dylib: ^0.3.2
  ffi: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8
