name: dart_serial_port
description: Serial Port for Dart (FFI bindings to libserialport,
  a minimal C-library created by the sigrok).
version: 0.1.0
homepage: https://github.com/jpnurmi/dart_serial_port
repository: https://github.com/jpnurmi/dart_serial_port
issue_tracker: https://github.com/jpnurmi/dart_serial_port/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dylib: ^0.3.1
  ffi: ^1.0.0

dev_dependencies:
  #ffigen: ^1.2.0
  lint: ^1.5.3
  test: ^1.16.7
